### ISSUE TITLE
Sites.

### ISSUE THREAD

**Issue by Krosovok** [Krosovok/MorningPaperRepo#4]
Which sites we will try to parse? We need ~5 sites to try, I suppose?

**Comment by Krosovok** [comment]
Maybe https://habrahabr.ru/ ? Many articles. Mostly text. Easy to show to others.

**Comment by Shandress** [comment]
For now, will we try processing images as well, or only text?

**Comment by Krosovok** [comment]
For now, let it be only text. There are sites and articles where there are no images or they don't contain any information. Images will be next step. When we will be shure that we can show at least what we have now.
